### ISSUE TITLE
Add basic design

### ISSUE THREAD

**Issue by mhstrkmp** [a-friday-with-donald/tronalddump-api#1]

**Comment by athnme** [comment]
Here is the figma link where u can checkout the initial design idea.

https://www.figma.com/file/DSkBtPKAxsNH0TrObA0JLo/Untitled?node-id=0%3A1

**Comment by athnme** [comment]
also here a little prototype preview link: https://www.figma.com/proto/DSkBtPKAxsNH0TrObA0JLo/Untitled?node-id=1%3A2&viewport=92%2C787%2C0.8185431361198425&scaling=min-zoom

**Comment by AlexisRoe** [comment]
thanks, a really cool design, we will take that with pleasure
